#[allow(unused, non_camel_case_types)]
pub enum HellStyle {
	w_0,
	w_0d5,
	w_1,
	w_1d5,
	w_2,
	w_2d5,
	w_3,
	w_3d5,
	w_4,
	w_5,
	w_6,
	w_7,
	w_8,
	w_9,
	w_10,
	w_px,
	w_auto,
	w_1s2,
	w_1s3,
	w_2s3,
	w_1s4,
	w_2s4,
	w_3s4,
	w_1s5,
	w_2s5,
	w_3s5,
	w_4s5,
	w_full,
	w_screen,
	w_min,
	w_max,
	w_fit,
	min_w_0,
	min_w_full,
	min_w_min,
	min_w_max,
	min_w_fit,
	max_w_0,
	max_w_none,
	max_w_xs,
	max_w_sm,
	max_w_md,
	max_w_lg,
	max_w_xl,
	max_w_2xl,
	max_w_3xl,
	max_w_4xl,
	max_w_5xl,
	max_w_6xl,
	max_w_7xl,
	max_w_full,
	max_w_max,
	max_w_min,
	max_w_fit,
	h_0,
	h_0d5,
	h_1,
	h_1d5,
	h_2,
	h_2d5,
	h_3,
	h_3d5,
	h_4,
	h_5,
	h_6,
	h_8,
	h_10,
	h_px,
	h_auto,
	h_1s2,
	h_1s3,
	h_2s3,
	h_1s4,
	h_2s4,
	h_3s4,
	h_1s5,
	h_2s5,
	h_3s5,
	h_4s5,
	h_full,
	h_screen,
	h_min,
	h_max,
	h_fit,
	min_h_0,
	min_h_full,
	min_h_screen,
	min_h_min,
	min_h_max,
	min_h_fit,
	max_h_0,
	max_h_0d5,
	max_h_1,
	max_h_1d5,
	max_h_2,
	max_h_2d5,
	max_h_3,
	max_h_3d5,
	max_h_4,
	max_h_5,
	max_h_6,
	max_h_8,
	max_h_10,
	max_h_px,
	max_h_auto,
	max_h_full,
	max_h_screen,
	max_h_min,
	max_h_max,
	max_h_fit,
	pos_static,
	pos_fixed,
	pos_absolute,
	pos_relative,
	pos_sticky,
	inset_0,
	inset_y_0,
	inset_x_0,
	top_0,
	right_0,
	bottom_0,
	left_0,
	p_0,
	p_0d5,
	p_1,
	p_1d5,
	p_2,
	p_2d5,
	p_3,
	p_3d5,
	p_4,
	p_5,
	p_6,
	p_8,
	p_10,
	m_auto,
	m_0,
	m_0d5,
	m_1,
	m_1d5,
	m_2,
	m_2d5,
	m_3,
	m_3d5,
	m_4,
	m_5,
	m_6,
	m_8,
	m_10,
	m_top_0,
	m_top_0d5,
	m_top_1,
	m_top_1d5,
	m_top_2,
	m_top_2d5,
	m_top_3,
	m_top_3d5,
	m_top_4,
	m_top_5,
	m_top_6,
	m_top_8,
	m_top_10,
	m_top_12,
	m_top_14,
	m_top_16,
	m_top_18,
	m_top_20,
	m_bottom_0,
	m_bottom_0d5,
	m_bottom_1,
	m_bottom_1d5,
	m_bottom_2,
	m_bottom_2d5,
	m_bottom_3,
	m_bottom_3d5,
	m_bottom_4,
	m_bottom_5,
	m_bottom_6,
	m_bottom_8,
	m_bottom_10,
	m_bottom_12,
	m_bottom_14,
	m_bottom_16,
	m_bottom_18,
	m_bottom_20,
	bg_primary_400,
	bg_secondary_400,
	bg_accent1_400,
	bg_accent2_400,
	text_primary_400,
	text_secondary_400,
	text_accent1_400,
	text_accent2_400,
	text_left,
	text_center,
	text_right,
	text_justify,
	text_xs,
	text_sm,
	text_base,
	text_lg,
	text_xl,
	text_2xl,
	text_3xl,
	text_4xl,
	text_5xl,
	text_6xl,
	text_7xl,
	text_8xl,
	text_9xl,
	flex,
	flex_row,
	flex_row_reverse,
	flex_col,
	flex_col_reverse,
	grid,
	grid_cols_1,
	grid_cols_2,
	grid_cols_3,
	grid_cols_4,
	grid_cols_5,
	grid_cols_6,
	grid_cols_7,
	grid_cols_8,
	grid_cols_9,
	grid_cols_10,
	grid_cols_11,
	grid_cols_12,
	grid_cols_none,
	grid_rows_1,
	grid_rows_2,
	grid_rows_3,
	grid_rows_4,
	grid_rows_5,
	grid_rows_6,
	grid_rows_none,
	col_auto,
	col_span_1,
	col_span_2,
	col_span_3,
	col_span_4,
	col_span_5,
	col_span_6,
	col_span_7,
	col_span_8,
	col_span_9,
	col_span_10,
	col_span_11,
	col_span_12,
	col_start_1,
	col_start_2,
	col_start_3,
	col_start_4,
	col_start_5,
	col_start_6,
	col_start_7,
	col_start_8,
	col_start_9,
	col_start_10,
	col_start_11,
	col_start_12,
	col_end_1,
	col_end_2,
	col_end_3,
	col_end_4,
	col_end_5,
	col_end_6,
	col_end_7,
	col_end_8,
	col_end_9,
	col_end_10,
	col_end_11,
	col_end_12,
	col_end_auto,
	row_auto,
	row_span_1,
	row_span_2,
	row_span_3,
	row_span_4,
	row_span_5,
	row_span_6,
	row_start_1,
	row_start_2,
	row_start_3,
	row_start_4,
	row_start_5,
	row_start_6,
	row_start_auto,
	row_end_1,
	row_end_2,
	row_end_3,
	row_end_4,
	row_end_5,
	row_end_6,
	row_end_auto,
	grid_flow_row,
	grid_flow_col,
	grid_flow_row_dense,
	grid_flow_col_dense,
	auto_cols_auto,
	auto_cols_min,
	auto_cols_max,
	auto_cols_fr,
	flex_1,
	flex_auto,
	flex_initial,
	flex_none,
	gap_0,
	gap_0d5,
	gap_1,
	gap_1d5,
	gap_2,
	gap_2d5,
	gap_3,
	gap_3d5,
	gap_4,
	justify_start,
	justify_center,
	justify_end,
	justify_between,
	justify_around,
	justify_evenly,
	justify_items_stretch,
	justify_items_start,
	justify_items_center,
	justify_items_end,
	justify_self_stretch,
	justify_self_start,
	justify_self_center,
	justify_self_end,
	justify_self_auto,
	content_start,
	content_center,
	content_end,
	content_between,
	content_around,
	content_evenly,
	items_stretch,
	items_start,
	items_center,
	items_end,
	items_baseline,
	border_solid,
	border_dashed,
	border_dotted,
	border_double,
	border_hidden,
	border_none,
	rounded_none,
	rounded_sm,
	rounded,
	rounded_md,
	rounded_lg,
	rounded_xl,
	rounded_2xl,
	rounded_3xl,
	rounded_full,
	border,
	border_0,
	border_2,
	border_4,
	border_8,
	border_t,
	border_t_0,
	border_t_2,
	border_t_4,
	border_t_8,
	border_r,
	border_r_0,
	border_r_2,
	border_r_4,
	border_r_8,
	border_b,
	border_b_0,
	border_b_2,
	border_b_4,
	border_b_8,
	border_l,
	border_l_0,
	border_l_2,
	border_l_4,
	border_l_8,
	border_transparent,
	border_primary_400,
	border_secondary_400,
	border_accent1_400,
	border_accent2_400,
}
impl AsRef<str> for HellStyle {
	fn as_ref(&self) -> &str {
		match &self {
			Self::w_0 => "w_0",
			Self::w_0d5 => "w_0d5",
			Self::w_1 => "w_1",
			Self::w_1d5 => "w_1d5",
			Self::w_2 => "w_2",
			Self::w_2d5 => "w_2d5",
			Self::w_3 => "w_3",
			Self::w_3d5 => "w_3d5",
			Self::w_4 => "w_4",
			Self::w_5 => "w_5",
			Self::w_6 => "w_6",
			Self::w_7 => "w_7",
			Self::w_8 => "w_8",
			Self::w_9 => "w_9",
			Self::w_10 => "w_10",
			Self::w_px => "w_px",
			Self::w_auto => "w_auto",
			Self::w_1s2 => "w_1s2",
			Self::w_1s3 => "w_1s3",
			Self::w_2s3 => "w_2s3",
			Self::w_1s4 => "w_1s4",
			Self::w_2s4 => "w_2s4",
			Self::w_3s4 => "w_3s4",
			Self::w_1s5 => "w_1s5",
			Self::w_2s5 => "w_2s5",
			Self::w_3s5 => "w_3s5",
			Self::w_4s5 => "w_4s5",
			Self::w_full => "w_full",
			Self::w_screen => "w_screen",
			Self::w_min => "w_min",
			Self::w_max => "w_max",
			Self::w_fit => "w_fit",
			Self::min_w_0 => "min_w_0",
			Self::min_w_full => "min_w_full",
			Self::min_w_min => "min_w_min",
			Self::min_w_max => "min_w_max",
			Self::min_w_fit => "min_w_fit",
			Self::max_w_0 => "max_w_0",
			Self::max_w_none => "max_w_none",
			Self::max_w_xs => "max_w_xs",
			Self::max_w_sm => "max_w_sm",
			Self::max_w_md => "max_w_md",
			Self::max_w_lg => "max_w_lg",
			Self::max_w_xl => "max_w_xl",
			Self::max_w_2xl => "max_w_2xl",
			Self::max_w_3xl => "max_w_3xl",
			Self::max_w_4xl => "max_w_4xl",
			Self::max_w_5xl => "max_w_5xl",
			Self::max_w_6xl => "max_w_6xl",
			Self::max_w_7xl => "max_w_7xl",
			Self::max_w_full => "max_w_full",
			Self::max_w_max => "max_w_max",
			Self::max_w_min => "max_w_min",
			Self::max_w_fit => "max_w_fit",
			Self::h_0 => "h_0",
			Self::h_0d5 => "h_0d5",
			Self::h_1 => "h_1",
			Self::h_1d5 => "h_1d5",
			Self::h_2 => "h_2",
			Self::h_2d5 => "h_2d5",
			Self::h_3 => "h_3",
			Self::h_3d5 => "h_3d5",
			Self::h_4 => "h_4",
			Self::h_5 => "h_5",
			Self::h_6 => "h_6",
			Self::h_8 => "h_8",
			Self::h_10 => "h_10",
			Self::h_px => "h_px",
			Self::h_auto => "h_auto",
			Self::h_1s2 => "h_1s2",
			Self::h_1s3 => "h_1s3",
			Self::h_2s3 => "h_2s3",
			Self::h_1s4 => "h_1s4",
			Self::h_2s4 => "h_2s4",
			Self::h_3s4 => "h_3s4",
			Self::h_1s5 => "h_1s5",
			Self::h_2s5 => "h_2s5",
			Self::h_3s5 => "h_3s5",
			Self::h_4s5 => "h_4s5",
			Self::h_full => "h_full",
			Self::h_screen => "h_screen",
			Self::h_min => "h_min",
			Self::h_max => "h_max",
			Self::h_fit => "h_fit",
			Self::min_h_0 => "min_h_0",
			Self::min_h_full => "min_h_full",
			Self::min_h_screen => "min_h_screen",
			Self::min_h_min => "min_h_min",
			Self::min_h_max => "min_h_max",
			Self::min_h_fit => "min_h_fit",
			Self::max_h_0 => "max_h_0",
			Self::max_h_0d5 => "max_h_0d5",
			Self::max_h_1 => "max_h_1",
			Self::max_h_1d5 => "max_h_1d5",
			Self::max_h_2 => "max_h_2",
			Self::max_h_2d5 => "max_h_2d5",
			Self::max_h_3 => "max_h_3",
			Self::max_h_3d5 => "max_h_3d5",
			Self::max_h_4 => "max_h_4",
			Self::max_h_5 => "max_h_5",
			Self::max_h_6 => "max_h_6",
			Self::max_h_8 => "max_h_8",
			Self::max_h_10 => "max_h_10",
			Self::max_h_px => "max_h_px",
			Self::max_h_auto => "max_h_auto",
			Self::max_h_full => "max_h_full",
			Self::max_h_screen => "max_h_screen",
			Self::max_h_min => "max_h_min",
			Self::max_h_max => "max_h_max",
			Self::max_h_fit => "max_h_fit",
			Self::pos_static => "pos_static",
			Self::pos_fixed => "pos_fixed",
			Self::pos_absolute => "pos_absolute",
			Self::pos_relative => "pos_relative",
			Self::pos_sticky => "pos_sticky",
			Self::inset_0 => "inset_0",
			Self::inset_y_0 => "inset_y_0",
			Self::inset_x_0 => "inset_x_0",
			Self::top_0 => "top_0",
			Self::right_0 => "right_0",
			Self::bottom_0 => "bottom_0",
			Self::left_0 => "left_0",
			Self::p_0 => "p_0",
			Self::p_0d5 => "p_0d5",
			Self::p_1 => "p_1",
			Self::p_1d5 => "p_1d5",
			Self::p_2 => "p_2",
			Self::p_2d5 => "p_2d5",
			Self::p_3 => "p_3",
			Self::p_3d5 => "p_3d5",
			Self::p_4 => "p_4",
			Self::p_5 => "p_5",
			Self::p_6 => "p_6",
			Self::p_8 => "p_8",
			Self::p_10 => "p_10",
			Self::m_auto => "m_auto",
			Self::m_0 => "m_0",
			Self::m_0d5 => "m_0d5",
			Self::m_1 => "m_1",
			Self::m_1d5 => "m_1d5",
			Self::m_2 => "m_2",
			Self::m_2d5 => "m_2d5",
			Self::m_3 => "m_3",
			Self::m_3d5 => "m_3d5",
			Self::m_4 => "m_4",
			Self::m_5 => "m_5",
			Self::m_6 => "m_6",
			Self::m_8 => "m_8",
			Self::m_10 => "m_10",
			Self::m_top_0 => "m_top_0",
			Self::m_top_0d5 => "m_top_0d5",
			Self::m_top_1 => "m_top_1",
			Self::m_top_1d5 => "m_top_1d5",
			Self::m_top_2 => "m_top_2",
			Self::m_top_2d5 => "m_top_2d5",
			Self::m_top_3 => "m_top_3",
			Self::m_top_3d5 => "m_top_3d5",
			Self::m_top_4 => "m_top_4",
			Self::m_top_5 => "m_top_5",
			Self::m_top_6 => "m_top_6",
			Self::m_top_8 => "m_top_8",
			Self::m_top_10 => "m_top_10",
			Self::m_top_12 => "m_top_12",
			Self::m_top_14 => "m_top_14",
			Self::m_top_16 => "m_top_16",
			Self::m_top_18 => "m_top_18",
			Self::m_top_20 => "m_top_20",
			Self::m_bottom_0 => "m_bottom_0",
			Self::m_bottom_0d5 => "m_bottom_0d5",
			Self::m_bottom_1 => "m_bottom_1",
			Self::m_bottom_1d5 => "m_bottom_1d5",
			Self::m_bottom_2 => "m_bottom_2",
			Self::m_bottom_2d5 => "m_bottom_2d5",
			Self::m_bottom_3 => "m_bottom_3",
			Self::m_bottom_3d5 => "m_bottom_3d5",
			Self::m_bottom_4 => "m_bottom_4",
			Self::m_bottom_5 => "m_bottom_5",
			Self::m_bottom_6 => "m_bottom_6",
			Self::m_bottom_8 => "m_bottom_8",
			Self::m_bottom_10 => "m_bottom_10",
			Self::m_bottom_12 => "m_bottom_12",
			Self::m_bottom_14 => "m_bottom_14",
			Self::m_bottom_16 => "m_bottom_16",
			Self::m_bottom_18 => "m_bottom_18",
			Self::m_bottom_20 => "m_bottom_20",
			Self::bg_primary_400 => "bg_primary_400",
			Self::bg_secondary_400 => "bg_secondary_400",
			Self::bg_accent1_400 => "bg_accent1_400",
			Self::bg_accent2_400 => "bg_accent2_400",
			Self::text_primary_400 => "text_primary_400",
			Self::text_secondary_400 => "text_secondary_400",
			Self::text_accent1_400 => "text_accent1_400",
			Self::text_accent2_400 => "text_accent2_400",
			Self::text_left => "text_left",
			Self::text_center => "text_center",
			Self::text_right => "text_right",
			Self::text_justify => "text_justify",
			Self::text_xs => "text_xs",
			Self::text_sm => "text_sm",
			Self::text_base => "text_base",
			Self::text_lg => "text_lg",
			Self::text_xl => "text_xl",
			Self::text_2xl => "text_2xl",
			Self::text_3xl => "text_3xl",
			Self::text_4xl => "text_4xl",
			Self::text_5xl => "text_5xl",
			Self::text_6xl => "text_6xl",
			Self::text_7xl => "text_7xl",
			Self::text_8xl => "text_8xl",
			Self::text_9xl => "text_9xl",
			Self::flex => "flex",
			Self::flex_row => "flex_row",
			Self::flex_row_reverse => "flex_row_reverse",
			Self::flex_col => "flex_col",
			Self::flex_col_reverse => "flex_col_reverse",
			Self::grid => "grid",
			Self::grid_cols_1 => "grid_cols_1",
			Self::grid_cols_2 => "grid_cols_2",
			Self::grid_cols_3 => "grid_cols_3",
			Self::grid_cols_4 => "grid_cols_4",
			Self::grid_cols_5 => "grid_cols_5",
			Self::grid_cols_6 => "grid_cols_6",
			Self::grid_cols_7 => "grid_cols_7",
			Self::grid_cols_8 => "grid_cols_8",
			Self::grid_cols_9 => "grid_cols_9",
			Self::grid_cols_10 => "grid_cols_10",
			Self::grid_cols_11 => "grid_cols_11",
			Self::grid_cols_12 => "grid_cols_12",
			Self::grid_cols_none => "grid_cols_none",
			Self::grid_rows_1 => "grid_rows_1",
			Self::grid_rows_2 => "grid_rows_2",
			Self::grid_rows_3 => "grid_rows_3",
			Self::grid_rows_4 => "grid_rows_4",
			Self::grid_rows_5 => "grid_rows_5",
			Self::grid_rows_6 => "grid_rows_6",
			Self::grid_rows_none => "grid_rows_none",
			Self::col_auto => "col_auto",
			Self::col_span_1 => "col_span_1",
			Self::col_span_2 => "col_span_2",
			Self::col_span_3 => "col_span_3",
			Self::col_span_4 => "col_span_4",
			Self::col_span_5 => "col_span_5",
			Self::col_span_6 => "col_span_6",
			Self::col_span_7 => "col_span_7",
			Self::col_span_8 => "col_span_8",
			Self::col_span_9 => "col_span_9",
			Self::col_span_10 => "col_span_10",
			Self::col_span_11 => "col_span_11",
			Self::col_span_12 => "col_span_12",
			Self::col_start_1 => "col_start_1",
			Self::col_start_2 => "col_start_2",
			Self::col_start_3 => "col_start_3",
			Self::col_start_4 => "col_start_4",
			Self::col_start_5 => "col_start_5",
			Self::col_start_6 => "col_start_6",
			Self::col_start_7 => "col_start_7",
			Self::col_start_8 => "col_start_8",
			Self::col_start_9 => "col_start_9",
			Self::col_start_10 => "col_start_10",
			Self::col_start_11 => "col_start_11",
			Self::col_start_12 => "col_start_12",
			Self::col_end_1 => "col_end_1",
			Self::col_end_2 => "col_end_2",
			Self::col_end_3 => "col_end_3",
			Self::col_end_4 => "col_end_4",
			Self::col_end_5 => "col_end_5",
			Self::col_end_6 => "col_end_6",
			Self::col_end_7 => "col_end_7",
			Self::col_end_8 => "col_end_8",
			Self::col_end_9 => "col_end_9",
			Self::col_end_10 => "col_end_10",
			Self::col_end_11 => "col_end_11",
			Self::col_end_12 => "col_end_12",
			Self::col_end_auto => "col_end_auto",
			Self::row_auto => "row_auto",
			Self::row_span_1 => "row_span_1",
			Self::row_span_2 => "row_span_2",
			Self::row_span_3 => "row_span_3",
			Self::row_span_4 => "row_span_4",
			Self::row_span_5 => "row_span_5",
			Self::row_span_6 => "row_span_6",
			Self::row_start_1 => "row_start_1",
			Self::row_start_2 => "row_start_2",
			Self::row_start_3 => "row_start_3",
			Self::row_start_4 => "row_start_4",
			Self::row_start_5 => "row_start_5",
			Self::row_start_6 => "row_start_6",
			Self::row_start_auto => "row_start_auto",
			Self::row_end_1 => "row_end_1",
			Self::row_end_2 => "row_end_2",
			Self::row_end_3 => "row_end_3",
			Self::row_end_4 => "row_end_4",
			Self::row_end_5 => "row_end_5",
			Self::row_end_6 => "row_end_6",
			Self::row_end_auto => "row_end_auto",
			Self::grid_flow_row => "grid_flow_row",
			Self::grid_flow_col => "grid_flow_col",
			Self::grid_flow_row_dense => "grid_flow_row_dense",
			Self::grid_flow_col_dense => "grid_flow_col_dense",
			Self::auto_cols_auto => "auto_cols_auto",
			Self::auto_cols_min => "auto_cols_min",
			Self::auto_cols_max => "auto_cols_max",
			Self::auto_cols_fr => "auto_cols_fr",
			Self::flex_1 => "flex_1",
			Self::flex_auto => "flex_auto",
			Self::flex_initial => "flex_initial",
			Self::flex_none => "flex_none",
			Self::gap_0 => "gap_0",
			Self::gap_0d5 => "gap_0d5",
			Self::gap_1 => "gap_1",
			Self::gap_1d5 => "gap_1d5",
			Self::gap_2 => "gap_2",
			Self::gap_2d5 => "gap_2d5",
			Self::gap_3 => "gap_3",
			Self::gap_3d5 => "gap_3d5",
			Self::gap_4 => "gap_4",
			Self::justify_start => "justify_start",
			Self::justify_center => "justify_center",
			Self::justify_end => "justify_end",
			Self::justify_between => "justify_between",
			Self::justify_around => "justify_around",
			Self::justify_evenly => "justify_evenly",
			Self::justify_items_stretch => "justify_items_stretch",
			Self::justify_items_start => "justify_items_start",
			Self::justify_items_center => "justify_items_center",
			Self::justify_items_end => "justify_items_end",
			Self::justify_self_stretch => "justify_self_stretch",
			Self::justify_self_start => "justify_self_start",
			Self::justify_self_center => "justify_self_center",
			Self::justify_self_end => "justify_self_end",
			Self::justify_self_auto => "justify_self_auto",
			Self::content_start => "content_start",
			Self::content_center => "content_center",
			Self::content_end => "content_end",
			Self::content_between => "content_between",
			Self::content_around => "content_around",
			Self::content_evenly => "content_evenly",
			Self::items_stretch => "items_stretch",
			Self::items_start => "items_start",
			Self::items_center => "items_center",
			Self::items_end => "items_end",
			Self::items_baseline => "items_baseline",
			Self::border_solid => "border_solid",
			Self::border_dashed => "border_dashed",
			Self::border_dotted => "border_dotted",
			Self::border_double => "border_double",
			Self::border_hidden => "border_hidden",
			Self::border_none => "border_none",
			Self::rounded_none => "rounded_none",
			Self::rounded_sm => "rounded_sm",
			Self::rounded => "rounded",
			Self::rounded_md => "rounded_md",
			Self::rounded_lg => "rounded_lg",
			Self::rounded_xl => "rounded_xl",
			Self::rounded_2xl => "rounded_2xl",
			Self::rounded_3xl => "rounded_3xl",
			Self::rounded_full => "rounded_full",
			Self::border => "border",
			Self::border_0 => "border_0",
			Self::border_2 => "border_2",
			Self::border_4 => "border_4",
			Self::border_8 => "border_8",
			Self::border_t => "border_t",
			Self::border_t_0 => "border_t_0",
			Self::border_t_2 => "border_t_2",
			Self::border_t_4 => "border_t_4",
			Self::border_t_8 => "border_t_8",
			Self::border_r => "border_r",
			Self::border_r_0 => "border_r_0",
			Self::border_r_2 => "border_r_2",
			Self::border_r_4 => "border_r_4",
			Self::border_r_8 => "border_r_8",
			Self::border_b => "border_b",
			Self::border_b_0 => "border_b_0",
			Self::border_b_2 => "border_b_2",
			Self::border_b_4 => "border_b_4",
			Self::border_b_8 => "border_b_8",
			Self::border_l => "border_l",
			Self::border_l_0 => "border_l_0",
			Self::border_l_2 => "border_l_2",
			Self::border_l_4 => "border_l_4",
			Self::border_l_8 => "border_l_8",
			Self::border_transparent => "border_transparent",
			Self::border_primary_400 => "border_primary_400",
			Self::border_secondary_400 => "border_secondary_400",
			Self::border_accent1_400 => "border_accent1_400",
			Self::border_accent2_400 => "border_accent2_400",
		}
	}
}
