#[allow(unused, non_camel_case_types)]
pub enum HellStyle {
	W_0,
	W_0D5,
	W_1,
	W_1D5,
	W_2,
	W_2D5,
	W_3,
	W_3D5,
	W_4,
	W_5,
	W_6,
	W_7,
	W_8,
	W_9,
	W_10,
	W_PX,
	W_AUTO,
	W_1S2,
	W_1S3,
	W_2S3,
	W_1S4,
	W_2S4,
	W_3S4,
	W_1S5,
	W_2S5,
	W_3S5,
	W_4S5,
	W_FULL,
	W_SCREEN,
	W_MIN,
	W_MAX,
	W_FIT,
	MIN_W_0,
	MIN_W_FULL,
	MIN_W_MIN,
	MIN_W_MAX,
	MIN_W_FIT,
	MAX_W_0,
	MAX_W_NONE,
	MAX_W_XS,
	MAX_W_SM,
	MAX_W_MD,
	MAX_W_LG,
	MAX_W_XL,
	MAX_W_2XL,
	MAX_W_3XL,
	MAX_W_4XL,
	MAX_W_5XL,
	MAX_W_6XL,
	MAX_W_7XL,
	MAX_W_FULL,
	MAX_W_MAX,
	MAX_W_MIN,
	MAX_W_FIT,
	H_0,
	H_0D5,
	H_1,
	H_1D5,
	H_2,
	H_2D5,
	H_3,
	H_3D5,
	H_4,
	H_5,
	H_6,
	H_8,
	H_10,
	H_PX,
	H_AUTO,
	H_1S2,
	H_1S3,
	H_2S3,
	H_1S4,
	H_2S4,
	H_3S4,
	H_1S5,
	H_2S5,
	H_3S5,
	H_4S5,
	H_FULL,
	H_SCREEN,
	H_MIN,
	H_MAX,
	H_FIT,
	MIN_H_0,
	MIN_H_FULL,
	MIN_H_SCREEN,
	MIN_H_MIN,
	MIN_H_MAX,
	MIN_H_FIT,
	MAX_H_0,
	MAX_H_0D5,
	MAX_H_1,
	MAX_H_1D5,
	MAX_H_2,
	MAX_H_2D5,
	MAX_H_3,
	MAX_H_3D5,
	MAX_H_4,
	MAX_H_5,
	MAX_H_6,
	MAX_H_8,
	MAX_H_10,
	MAX_H_PX,
	MAX_H_AUTO,
	MAX_H_FULL,
	MAX_H_SCREEN,
	MAX_H_MIN,
	MAX_H_MAX,
	MAX_H_FIT,
	P_0,
	P_0D5,
	P_1,
	P_1D5,
	P_2,
	P_2D5,
	P_3,
	P_3D5,
	P_4,
	P_5,
	P_6,
	P_8,
	P_10,
	M_0,
	M_0D5,
	M_1,
	M_1D5,
	M_2,
	M_2D5,
	M_3,
	M_3D5,
	M_4,
	M_5,
	M_6,
	M_8,
	M_10,
	BG_PRIM_400,
	BG_SEC_400,
	BG_HL1_400,
	BG_HL2_400,
	TEXT_PRIM_400,
	TEXT_SEC_400,
	TEXT_HL1_400,
	TEXT_HL2_400,
	TEXT_LEFT,
	TEXT_CENTER,
	TEXT_RIGHT,
	TEXT_JUSTIFY,
	TEXT_XS,
	TEXT_SM,
	TEXT_BASE,
	TEXT_LG,
	TEXT_XL,
	TEXT_2XL,
	TEXT_3XL,
	TEXT_4XL,
	TEXT_5XL,
	TEXT_6XL,
	TEXT_7XL,
	TEXT_8XL,
	TEXT_9XL,
	FLEX_ROW,
	FLEX_ROW_REVERSE,
	FLEX_COL,
	FLEX_COL_REVERSE,
	GRID,
	GRID_COLS_1,
	GRID_COLS_2,
	GRID_COLS_3,
	GRID_COLS_4,
	GRID_COLS_5,
	GRID_COLS_6,
	GRID_COLS_7,
	GRID_COLS_8,
	GRID_COLS_9,
	GRID_COLS_10,
	GRID_COLS_11,
	GRID_COLS_12,
	GRID_COLS_NONE,
	GRID_ROWS_1,
	GRID_ROWS_2,
	GRID_ROWS_3,
	GRID_ROWS_4,
	GRID_ROWS_5,
	GRID_ROWS_6,
	GRID_ROWS_NONE,
	COL_AUTO,
	COL_SPAN_1,
	COL_SPAN_2,
	COL_SPAN_3,
	COL_SPAN_4,
	COL_SPAN_5,
	COL_SPAN_6,
	COL_SPAN_7,
	COL_SPAN_8,
	COL_SPAN_9,
	COL_SPAN_10,
	COL_SPAN_11,
	COL_SPAN_12,
	COL_START_1,
	COL_START_2,
	COL_START_3,
	COL_START_4,
	COL_START_5,
	COL_START_6,
	COL_START_7,
	COL_START_8,
	COL_START_9,
	COL_START_10,
	COL_START_11,
	COL_START_12,
	COL_END_1,
	COL_END_2,
	COL_END_3,
	COL_END_4,
	COL_END_5,
	COL_END_6,
	COL_END_7,
	COL_END_8,
	COL_END_9,
	COL_END_10,
	COL_END_11,
	COL_END_12,
	COL_END_AUTO,
	ROW_AUTO,
	ROW_SPAN_1,
	ROW_SPAN_2,
	ROW_SPAN_3,
	ROW_SPAN_4,
	ROW_SPAN_5,
	ROW_SPAN_6,
	ROW_START_1,
	ROW_START_2,
	ROW_START_3,
	ROW_START_4,
	ROW_START_5,
	ROW_START_6,
	ROW_START_AUTO,
	ROW_END_1,
	ROW_END_2,
	ROW_END_3,
	ROW_END_4,
	ROW_END_5,
	ROW_END_6,
	ROW_END_AUTO,
	GRID_FLOW_ROW,
	GRID_FLOW_COL,
	GRID_FLOW_ROW_DENSE,
	GRID_FLOW_COL_DENSE,
	AUTO_COLS_AUTO,
	AUTO_COLS_MIN,
	AUTO_COLS_MAX,
	AUTO_COLS_FR,
	FLEX_1,
	FLEX_AUTO,
	FLEX_INITIAL,
	FLEX_NONE,
	GAP_0,
	GAP_0D5,
	GAP_1,
	GAP_1D5,
	GAP_2,
	GAP_2D5,
	GAP_3,
	GAP_3D5,
	GAP_4,
	JUSTIFY_START,
	JUSTIFY_CENTER,
	JUSTIFY_END,
	JUSTIFY_BETWEEN,
	JUSTIFY_AROUND,
	JUSTIFY_EVENLY,
	JUSTIFY_ITEMS_STRETCH,
	JUSTIFY_ITEMS_START,
	JUSTIFY_ITEMS_CENTER,
	JUSTIFY_ITEMS_END,
	JUSTIFY_SELF_STRETCH,
	JUSTIFY_SELF_START,
	JUSTIFY_SELF_CENTER,
	JUSTIFY_SELF_END,
	JUSTIFY_SELF_AUTO,
	CONTENT_START,
	CONTENT_CENTER,
	CONTENT_END,
	CONTENT_BETWEEN,
	CONTENT_AROUND,
	CONTENT_EVENLY,
	ITEMS_STRETCH,
	ITEMS_START,
	ITEMS_CENTER,
	ITEMS_END,
	ITEMS_BASELINE,
	ROUNDED_NONE,
	ROUNDED_SM,
	ROUNDED,
	ROUNDED_MD,
	ROUNDED_LG,
	ROUNDED_XL,
	ROUNDED_2XL,
	ROUNDED_3XL,
	ROUNDED_FULL,
	BORDER,
	BORDER_0,
	BORDER_2,
	BORDER_4,
	BORDER_8,
	BORDER_TRANSPARENT,
	BORDER_PRIM_400,
	BORDER_SEC_400,
	BORDER_HL1_400,
	BORDER_HL2_400,
}
impl AsRef<str> for HellStyle {
	fn as_ref(&self) -> &str {
		match &self {
			Self::W_0 => "w_0",
			Self::W_0D5 => "w_0d5",
			Self::W_1 => "w_1",
			Self::W_1D5 => "w_1d5",
			Self::W_2 => "w_2",
			Self::W_2D5 => "w_2d5",
			Self::W_3 => "w_3",
			Self::W_3D5 => "w_3d5",
			Self::W_4 => "w_4",
			Self::W_5 => "w_5",
			Self::W_6 => "w_6",
			Self::W_7 => "w_7",
			Self::W_8 => "w_8",
			Self::W_9 => "w_9",
			Self::W_10 => "w_10",
			Self::W_PX => "w_px",
			Self::W_AUTO => "w_auto",
			Self::W_1S2 => "w_1s2",
			Self::W_1S3 => "w_1s3",
			Self::W_2S3 => "w_2s3",
			Self::W_1S4 => "w_1s4",
			Self::W_2S4 => "w_2s4",
			Self::W_3S4 => "w_3s4",
			Self::W_1S5 => "w_1s5",
			Self::W_2S5 => "w_2s5",
			Self::W_3S5 => "w_3s5",
			Self::W_4S5 => "w_4s5",
			Self::W_FULL => "w_full",
			Self::W_SCREEN => "w_screen",
			Self::W_MIN => "w_min",
			Self::W_MAX => "w_max",
			Self::W_FIT => "w_fit",
			Self::MIN_W_0 => "min_w_0",
			Self::MIN_W_FULL => "min_w_full",
			Self::MIN_W_MIN => "min_w_min",
			Self::MIN_W_MAX => "min_w_max",
			Self::MIN_W_FIT => "min_w_fit",
			Self::MAX_W_0 => "max_w_0",
			Self::MAX_W_NONE => "max_w_none",
			Self::MAX_W_XS => "max_w_xs",
			Self::MAX_W_SM => "max_w_sm",
			Self::MAX_W_MD => "max_w_md",
			Self::MAX_W_LG => "max_w_lg",
			Self::MAX_W_XL => "max_w_xl",
			Self::MAX_W_2XL => "max_w_2xl",
			Self::MAX_W_3XL => "max_w_3xl",
			Self::MAX_W_4XL => "max_w_4xl",
			Self::MAX_W_5XL => "max_w_5xl",
			Self::MAX_W_6XL => "max_w_6xl",
			Self::MAX_W_7XL => "max_w_7xl",
			Self::MAX_W_FULL => "max_w_full",
			Self::MAX_W_MAX => "max_w_max",
			Self::MAX_W_MIN => "max_w_min",
			Self::MAX_W_FIT => "max_w_fit",
			Self::H_0 => "h_0",
			Self::H_0D5 => "h_0d5",
			Self::H_1 => "h_1",
			Self::H_1D5 => "h_1d5",
			Self::H_2 => "h_2",
			Self::H_2D5 => "h_2d5",
			Self::H_3 => "h_3",
			Self::H_3D5 => "h_3d5",
			Self::H_4 => "h_4",
			Self::H_5 => "h_5",
			Self::H_6 => "h_6",
			Self::H_8 => "h_8",
			Self::H_10 => "h_10",
			Self::H_PX => "h_px",
			Self::H_AUTO => "h_auto",
			Self::H_1S2 => "h_1s2",
			Self::H_1S3 => "h_1s3",
			Self::H_2S3 => "h_2s3",
			Self::H_1S4 => "h_1s4",
			Self::H_2S4 => "h_2s4",
			Self::H_3S4 => "h_3s4",
			Self::H_1S5 => "h_1s5",
			Self::H_2S5 => "h_2s5",
			Self::H_3S5 => "h_3s5",
			Self::H_4S5 => "h_4s5",
			Self::H_FULL => "h_full",
			Self::H_SCREEN => "h_screen",
			Self::H_MIN => "h_min",
			Self::H_MAX => "h_max",
			Self::H_FIT => "h_fit",
			Self::MIN_H_0 => "min_h_0",
			Self::MIN_H_FULL => "min_h_full",
			Self::MIN_H_SCREEN => "min_h_screen",
			Self::MIN_H_MIN => "min_h_min",
			Self::MIN_H_MAX => "min_h_max",
			Self::MIN_H_FIT => "min_h_fit",
			Self::MAX_H_0 => "max_h_0",
			Self::MAX_H_0D5 => "max_h_0d5",
			Self::MAX_H_1 => "max_h_1",
			Self::MAX_H_1D5 => "max_h_1d5",
			Self::MAX_H_2 => "max_h_2",
			Self::MAX_H_2D5 => "max_h_2d5",
			Self::MAX_H_3 => "max_h_3",
			Self::MAX_H_3D5 => "max_h_3d5",
			Self::MAX_H_4 => "max_h_4",
			Self::MAX_H_5 => "max_h_5",
			Self::MAX_H_6 => "max_h_6",
			Self::MAX_H_8 => "max_h_8",
			Self::MAX_H_10 => "max_h_10",
			Self::MAX_H_PX => "max_h_px",
			Self::MAX_H_AUTO => "max_h_auto",
			Self::MAX_H_FULL => "max_h_full",
			Self::MAX_H_SCREEN => "max_h_screen",
			Self::MAX_H_MIN => "max_h_min",
			Self::MAX_H_MAX => "max_h_max",
			Self::MAX_H_FIT => "max_h_fit",
			Self::P_0 => "p_0",
			Self::P_0D5 => "p_0d5",
			Self::P_1 => "p_1",
			Self::P_1D5 => "p_1d5",
			Self::P_2 => "p_2",
			Self::P_2D5 => "p_2d5",
			Self::P_3 => "p_3",
			Self::P_3D5 => "p_3d5",
			Self::P_4 => "p_4",
			Self::P_5 => "p_5",
			Self::P_6 => "p_6",
			Self::P_8 => "p_8",
			Self::P_10 => "p_10",
			Self::M_0 => "m_0",
			Self::M_0D5 => "m_0d5",
			Self::M_1 => "m_1",
			Self::M_1D5 => "m_1d5",
			Self::M_2 => "m_2",
			Self::M_2D5 => "m_2d5",
			Self::M_3 => "m_3",
			Self::M_3D5 => "m_3d5",
			Self::M_4 => "m_4",
			Self::M_5 => "m_5",
			Self::M_6 => "m_6",
			Self::M_8 => "m_8",
			Self::M_10 => "m_10",
			Self::BG_PRIM_400 => "bg_prim_400",
			Self::BG_SEC_400 => "bg_sec_400",
			Self::BG_HL1_400 => "bg_hl1_400",
			Self::BG_HL2_400 => "bg_hl2_400",
			Self::TEXT_PRIM_400 => "text_prim_400",
			Self::TEXT_SEC_400 => "text_sec_400",
			Self::TEXT_HL1_400 => "text_hl1_400",
			Self::TEXT_HL2_400 => "text_hl2_400",
			Self::TEXT_LEFT => "text_left",
			Self::TEXT_CENTER => "text_center",
			Self::TEXT_RIGHT => "text_right",
			Self::TEXT_JUSTIFY => "text_justify",
			Self::TEXT_XS => "text_xs",
			Self::TEXT_SM => "text_sm",
			Self::TEXT_BASE => "text_base",
			Self::TEXT_LG => "text_lg",
			Self::TEXT_XL => "text_xl",
			Self::TEXT_2XL => "text_2xl",
			Self::TEXT_3XL => "text_3xl",
			Self::TEXT_4XL => "text_4xl",
			Self::TEXT_5XL => "text_5xl",
			Self::TEXT_6XL => "text_6xl",
			Self::TEXT_7XL => "text_7xl",
			Self::TEXT_8XL => "text_8xl",
			Self::TEXT_9XL => "text_9xl",
			Self::FLEX_ROW => "flex_row",
			Self::FLEX_ROW_REVERSE => "flex_row_reverse",
			Self::FLEX_COL => "flex_col",
			Self::FLEX_COL_REVERSE => "flex_col_reverse",
			Self::GRID => "grid",
			Self::GRID_COLS_1 => "grid_cols_1",
			Self::GRID_COLS_2 => "grid_cols_2",
			Self::GRID_COLS_3 => "grid_cols_3",
			Self::GRID_COLS_4 => "grid_cols_4",
			Self::GRID_COLS_5 => "grid_cols_5",
			Self::GRID_COLS_6 => "grid_cols_6",
			Self::GRID_COLS_7 => "grid_cols_7",
			Self::GRID_COLS_8 => "grid_cols_8",
			Self::GRID_COLS_9 => "grid_cols_9",
			Self::GRID_COLS_10 => "grid_cols_10",
			Self::GRID_COLS_11 => "grid_cols_11",
			Self::GRID_COLS_12 => "grid_cols_12",
			Self::GRID_COLS_NONE => "grid_cols_none",
			Self::GRID_ROWS_1 => "grid_rows_1",
			Self::GRID_ROWS_2 => "grid_rows_2",
			Self::GRID_ROWS_3 => "grid_rows_3",
			Self::GRID_ROWS_4 => "grid_rows_4",
			Self::GRID_ROWS_5 => "grid_rows_5",
			Self::GRID_ROWS_6 => "grid_rows_6",
			Self::GRID_ROWS_NONE => "grid_rows_none",
			Self::COL_AUTO => "col_auto",
			Self::COL_SPAN_1 => "col_span_1",
			Self::COL_SPAN_2 => "col_span_2",
			Self::COL_SPAN_3 => "col_span_3",
			Self::COL_SPAN_4 => "col_span_4",
			Self::COL_SPAN_5 => "col_span_5",
			Self::COL_SPAN_6 => "col_span_6",
			Self::COL_SPAN_7 => "col_span_7",
			Self::COL_SPAN_8 => "col_span_8",
			Self::COL_SPAN_9 => "col_span_9",
			Self::COL_SPAN_10 => "col_span_10",
			Self::COL_SPAN_11 => "col_span_11",
			Self::COL_SPAN_12 => "col_span_12",
			Self::COL_START_1 => "col_start_1",
			Self::COL_START_2 => "col_start_2",
			Self::COL_START_3 => "col_start_3",
			Self::COL_START_4 => "col_start_4",
			Self::COL_START_5 => "col_start_5",
			Self::COL_START_6 => "col_start_6",
			Self::COL_START_7 => "col_start_7",
			Self::COL_START_8 => "col_start_8",
			Self::COL_START_9 => "col_start_9",
			Self::COL_START_10 => "col_start_10",
			Self::COL_START_11 => "col_start_11",
			Self::COL_START_12 => "col_start_12",
			Self::COL_END_1 => "col_end_1",
			Self::COL_END_2 => "col_end_2",
			Self::COL_END_3 => "col_end_3",
			Self::COL_END_4 => "col_end_4",
			Self::COL_END_5 => "col_end_5",
			Self::COL_END_6 => "col_end_6",
			Self::COL_END_7 => "col_end_7",
			Self::COL_END_8 => "col_end_8",
			Self::COL_END_9 => "col_end_9",
			Self::COL_END_10 => "col_end_10",
			Self::COL_END_11 => "col_end_11",
			Self::COL_END_12 => "col_end_12",
			Self::COL_END_AUTO => "col_end_auto",
			Self::ROW_AUTO => "row_auto",
			Self::ROW_SPAN_1 => "row_span_1",
			Self::ROW_SPAN_2 => "row_span_2",
			Self::ROW_SPAN_3 => "row_span_3",
			Self::ROW_SPAN_4 => "row_span_4",
			Self::ROW_SPAN_5 => "row_span_5",
			Self::ROW_SPAN_6 => "row_span_6",
			Self::ROW_START_1 => "row_start_1",
			Self::ROW_START_2 => "row_start_2",
			Self::ROW_START_3 => "row_start_3",
			Self::ROW_START_4 => "row_start_4",
			Self::ROW_START_5 => "row_start_5",
			Self::ROW_START_6 => "row_start_6",
			Self::ROW_START_AUTO => "row_start_auto",
			Self::ROW_END_1 => "row_end_1",
			Self::ROW_END_2 => "row_end_2",
			Self::ROW_END_3 => "row_end_3",
			Self::ROW_END_4 => "row_end_4",
			Self::ROW_END_5 => "row_end_5",
			Self::ROW_END_6 => "row_end_6",
			Self::ROW_END_AUTO => "row_end_auto",
			Self::GRID_FLOW_ROW => "grid_flow_row",
			Self::GRID_FLOW_COL => "grid_flow_col",
			Self::GRID_FLOW_ROW_DENSE => "grid_flow_row_dense",
			Self::GRID_FLOW_COL_DENSE => "grid_flow_col_dense",
			Self::AUTO_COLS_AUTO => "auto_cols_auto",
			Self::AUTO_COLS_MIN => "auto_cols_min",
			Self::AUTO_COLS_MAX => "auto_cols_max",
			Self::AUTO_COLS_FR => "auto_cols_fr",
			Self::FLEX_1 => "flex_1",
			Self::FLEX_AUTO => "flex_auto",
			Self::FLEX_INITIAL => "flex_initial",
			Self::FLEX_NONE => "flex_none",
			Self::GAP_0 => "gap_0",
			Self::GAP_0D5 => "gap_0d5",
			Self::GAP_1 => "gap_1",
			Self::GAP_1D5 => "gap_1d5",
			Self::GAP_2 => "gap_2",
			Self::GAP_2D5 => "gap_2d5",
			Self::GAP_3 => "gap_3",
			Self::GAP_3D5 => "gap_3d5",
			Self::GAP_4 => "gap_4",
			Self::JUSTIFY_START => "justify_start",
			Self::JUSTIFY_CENTER => "justify_center",
			Self::JUSTIFY_END => "justify_end",
			Self::JUSTIFY_BETWEEN => "justify_between",
			Self::JUSTIFY_AROUND => "justify_around",
			Self::JUSTIFY_EVENLY => "justify_evenly",
			Self::JUSTIFY_ITEMS_STRETCH => "justify_items_stretch",
			Self::JUSTIFY_ITEMS_START => "justify_items_start",
			Self::JUSTIFY_ITEMS_CENTER => "justify_items_center",
			Self::JUSTIFY_ITEMS_END => "justify_items_end",
			Self::JUSTIFY_SELF_STRETCH => "justify_self_stretch",
			Self::JUSTIFY_SELF_START => "justify_self_start",
			Self::JUSTIFY_SELF_CENTER => "justify_self_center",
			Self::JUSTIFY_SELF_END => "justify_self_end",
			Self::JUSTIFY_SELF_AUTO => "justify_self_auto",
			Self::CONTENT_START => "content_start",
			Self::CONTENT_CENTER => "content_center",
			Self::CONTENT_END => "content_end",
			Self::CONTENT_BETWEEN => "content_between",
			Self::CONTENT_AROUND => "content_around",
			Self::CONTENT_EVENLY => "content_evenly",
			Self::ITEMS_STRETCH => "items_stretch",
			Self::ITEMS_START => "items_start",
			Self::ITEMS_CENTER => "items_center",
			Self::ITEMS_END => "items_end",
			Self::ITEMS_BASELINE => "items_baseline",
			Self::ROUNDED_NONE => "rounded_none",
			Self::ROUNDED_SM => "rounded_sm",
			Self::ROUNDED => "rounded",
			Self::ROUNDED_MD => "rounded_md",
			Self::ROUNDED_LG => "rounded_lg",
			Self::ROUNDED_XL => "rounded_xl",
			Self::ROUNDED_2XL => "rounded_2xl",
			Self::ROUNDED_3XL => "rounded_3xl",
			Self::ROUNDED_FULL => "rounded_full",
			Self::BORDER => "border",
			Self::BORDER_0 => "border_0",
			Self::BORDER_2 => "border_2",
			Self::BORDER_4 => "border_4",
			Self::BORDER_8 => "border_8",
			Self::BORDER_TRANSPARENT => "border_transparent",
			Self::BORDER_PRIM_400 => "border_prim_400",
			Self::BORDER_SEC_400 => "border_sec_400",
			Self::BORDER_HL1_400 => "border_hl1_400",
			Self::BORDER_HL2_400 => "border_hl2_400",
		}
	}
}
