[package]
name = "hell_store"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hell_error = { workspace = true, features = ["native"] }
tokio.workspace = true
